config/routes.rb
Rails.application.routes.draw do
  root 'books#index'
  resources :books, only: %i[index new create show destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  include BookSearch::Engine
  include Elasticsearch::Model::Callbacks
  validates :isbn, presence: true
end

app/models/concerns/book_search/engine.rb
module BookSearch
  module Engine
    extend ActiveSupport::Concern

    included do
      include Elasticsearch::Model
      # index名
      index_name "es_book_#{Rails.env}"
      # mapping情報
      settings do
        mappings dynamic: 'false' do
          indexes :id,        type: 'integer'
          indexes :isbn,      type: 'text'
          indexes :title,     type: 'text', analyzer: 'kuromoji'
          indexes :publisher, type: 'text', analyzer: 'kuromoji'
          indexes :pubdate,   type: 'text'
          indexes :cover,     type: 'text'
          indexes :author,    type: 'text', analyzer: 'kuromoji'
        end
      end
      # mappingの定義に合わせてindexするドキュメントの情報を生成する
      def as_indexed_json(*)
        attributes
          .symbolize_keys
          .slice(:id, :isbn, :title, :publisher, :pubdate, :cover, :author)
      end
    end

    class_methods do
      # ④indexを作成するメソッド
      def create_index!
        client = __elasticsearch__.client
        # すでにindexを作成済みの場合は削除する
        begin
          client.indices.delete index: index_name
        rescue StandardError
          nil
        end
        # indexを作成する
        client.indices.create(index: index_name,
                              body: {
                                settings: settings.to_hash,
                                mappings: mappings.to_hash
                              })
      end
    end

    def search(query)
      elasticsearch__.search({
                               query: {
                                 multi_match: {
                                   fields: %w[isbn title publisher pubdate author],
                                   type: 'cross_fields',
                                   query: query,
                                   operator: 'and'
                                 }
                               }
                             })
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # 200 Success
  def response_success(class_name, action_name)
    flash[:success] = "Success #{class_name.capitalize} #{action_name.capitalize}"
  end

  # 500 Internal Server Error
  def response_internal_server_error
    flash[:warning] = '書籍が見つからないため登録できませんでした'
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = if query.present?
               Book.search(query).records
             else
               Book.all
             end
  end

  def new
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    book = Book.new(book_params)
    json_api_data = call_openbd_api(book.isbn)
    if error_call_api(json_api_data)
      response_internal_server_error
    else
      Book.create(
        get_json(json_api_data)
      )
      response_success(:book, :create)
    end
    redirect_to root_path
  end

  def destroy
    Book.find(params[:id]).destroy
    redirect_to root_path
  end

  private

  def query
    @query ||= params[:query]
  end

  def book_params
    params.require(:book).permit(:isbn)
  end

  def get_json(json_api_data)
    # 呼び出しが成功した場合、必要な情報だけを抜き出して新しいJSONを作成する
    {
      isbn: json_api_data[0]['summary']['isbn'],
      title: json_api_data[0]['summary']['title'],
      publisher: json_api_data[0]['summary']['publisher'],
      pubdate: json_api_data[0]['summary']['pubdate'],
      cover: json_api_data[0]['summary']['cover'],
      author: json_api_data[0]['summary']['author']
    }
  end

  def call_openbd_api(isbn)
    url = "https://api.openbd.jp/v1/get?isbn=#{isbn}"
    uri = URI.parse(url)
    response = Net::HTTP.get(uri)
    JSON.parse(response)
  end

  def error_call_api(json_api_data)
    # 呼び出しが失敗した場合
    response_internal_server_error if json_api_data.nil?
    # 検索結果が0だった場合
    response_internal_server_error if json_api_data[0].nil?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_index.html.erb
<div class="block">
  <table class='table is-bordered is-striped is-hoverable'>
    <thead>
      <tr>
        <th class="table-index">index</th>
        <th>Title</th>
        <th>Button</th>
      </tr>
    </thead>
    <tbody>
      <% @books.each.with_index(1) do |book, index| %>
      <tr>
        <th class="table-index"><%= "#{index}" %></th>
        <td>
        <%= link_to book.title, book_path(book), remote: true %>
        </td>
        <td class="table-index inverted">
        <%= link_to 'DELETE', book_path(book), method: :delete, data: {confirm: '本当に削除しますか?'} %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/books/_modal.html.erb
<div class="modal">
	<div class="modal-background"></div>
	<div class="modal-card">
		<header class="modal-card-head">
			<p class="modal-card-title">書籍詳細</p>
			<button class="delete" aria-label="close"></button>
		</header>
		<section class="modal-card-body">
			<div class="container">
				<table class='table is-hoverable'>
					<tbody>
						<tr>
							<th>書籍名</th>
							<td><%= @book.title %></td>
						</tr>
						<tr>
							<th>表紙</th>
							<td><%= image_tag @book.cover, alt: '表紙' %></td>
						</tr>
						<tr>
							<th>著者</th>
							<td><%= @book.author %></td>
						</tr>
						<tr>
							<th>出版社</th>
							<td><%= @book.publisher %></td>
						</tr>
						<tr>
							<th>出版日</th>
							<td><%= @book.pubdate %></td>
						</tr>
						<tr>
							<th>ISBN</th>
							<td><%= @book.isbn %></td>
						</tr>
						<tr>
							<th>登録日</th>
							<td><%= l @book.created_at, format: :short %></td>
						</tr>
					</tbody>
				</table>
			</div>
		</section>
		<footer class="modal-card-foot">
		<div class="container has-text-centered">
			<button class="button">画面のどこをクリックしても閉じます</button>
		</div>
		</footer>
	</div>
</div>

app/views/books/_new.html.erb
<div class="modal modal-new">
  <div class="modal-background"></div>
  <div class="modal-card">
    <header class="modal-card-head">
      <h1 class="modal-card-title">書籍追加</h1>
      <button class="delete" aria-label="close" id="delete"></button>
    </header>
    <section class="modal-card-body">
      <div class="container">
        <div class="control p-6">
          <%= form_with(url: books_path, model: Book.new) do |form| %>
          <div class="control pb-6">
            <%= form.label :isbn, "ISBNコード", class: "label" %>
            <%= form.text_field :isbn, class: "input", placeholder: "ISBNコードを入力" %>
          </div>
          <%= form.submit :"登録", class: "button is-fullwidth" %>
          <% end %>
        </div>
      </div>
    </section>
  </div>
</div>
</div>

app/views/books/index.html.erb
<!-- 検索フォーム -->
<div class="block">
  <%= form_tag(books_path, method: :get, class: "field has-addons has-addons-centered") do %>
  <div class="control">
    <%= text_field_tag :query, @query, class: "input", placeholder: "本を検索する" %>
  </div>
  <div class="control">
    <%= submit_tag "検索", class: "button" %>
  </div>
  <% end %>
</div>

<!-- タブ -->
<div class="block">
  <div class="tabs inverted is-centered">
    <ul>
      <li class="tab_index"><%= link_to "書籍一覧", books_path, remote: true %></li>
      <li class="tab_new"><%= link_to "書籍追加", new_book_path, remote: true %></li>
    </ul>
  </div>
</div>

<!-- タブコンテンツ一覧 -->
<div id="tab_contents"><%= render 'index' %></div>

<!-- モーダルウインドウ -->
<div id="modal_show"></div>
<div id="modal_new"></div>

app/views/books/index.js.erb
var tab_contents_id 	 = document.getElementById('tab_contents');
var tab_contents_class = document.getElementsByClassName('tab_index');
var tab_btn            = document.querySelector('.tab_new');

tab_contents_id.innerHTML = ("<%= escape_javascript(render 'index') %>");

// クリックされたら書籍一覧タブをアクティブ化する
tab_contents_class[0].classList.add('is-active');

// 書籍追加タブがクリックされたときにis-activeを削除して書籍一覧タブを非アクティブ化する
tab_btn.addEventListener('click', () => {
  tab_contents_class[0].classList.remove('is-active');
});

app/views/books/new.html.erb
<h1>書籍登録</h1>

<%= form_with(model: @book, local: true) do |form| %>
  <div>
    <%= form.label :isbn %>
    <%= form.text_field :isbn %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/new.js.erb
var modal_id 		= document.getElementById('modal_new');
var modal_class = document.getElementsByClassName('modal-new');

// id属性modalの中身を_modalの内容に置き換える
modal_id.innerHTML = "<%= escape_javascript(render 'new') %>";

// bulmaの修飾子{is-active}をclass属性に付与してモーダルウィンドウを表示する
modal_class[0].classList.add('is-active');

// 画面をクリックしたときにis-activeを削除してモーダルウインドウを閉じる
document.getElementById('delete').onclick = function()  {
  modal_class[0].classList.remove('is-active');
};

app/views/books/show.js.erb
var modal_id 		= document.getElementById('modal_show');
var modal_class = document.getElementsByClassName('modal');

// id属性modalの中身を_modalの内容に置き換える
modal_id.innerHTML = "<%= escape_javascript(render 'modal', locals: { book: @book}) %>";

// bulmaの修飾子{is-active}をclass属性に付与してモーダルウィンドウを表示する
modal_class[0].classList.add('is-active');

// 画面をクリックしたときにis-activeを削除してモーダルウインドウを閉じる
modal_id.addEventListener('click', () => {
  modal_class[0].classList.remove('is-active');
});

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="UTF-8">
  <title>BookManagement</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="manifest" href="/manifest.json" />
</head>

<body>
  <%= render 'shared/navbar' %>
  <%= render 'shared/error_message' %>
  <%= yield %>
  <%= render 'shared/footer' %>
</body>

</html>

app/views/shared/_error_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="notification is-<%= message_type %> is-light">
  	<%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
	<div class="content has-text-centered">
		<p>
			<strong>BookManagement</strong> by
			<%= link_to 'https://github.com/suke0828' do %>
			suke0828 <i class="fab fa-github"></i>
			<% end %>
			
			The repository by Github
			<%= link_to 'https://github.com/suke0828/Book_management' do %>
			Book_management <i class="fab fa-github"></i>
			<% end %>
		</p>
	</div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
	<div class="navbar-brand">
		<div class="navbar-item title">
			<%= link_to 'Book Management', root_path %>
		</div>
	</div>
</nav>